export const mockDataProduk = [
  {
    id: 1,
    nama_produk: "Smartphone X1",
    kategori: "Elektronik",
    harga: 5000000,
    stok: 25,
    rating: 4.5,
  },
  {
    id: 2,
    nama_produk: "Laptop Pro 14",
    kategori: "Elektronik",
    harga: 12000000,
    stok: 10,
    rating: 4.8,
  },
  {
    id: 3,
    nama_produk: "Kemeja Flanel Blue",
    kategori: "Pakaian",
    harga: 250000,
    stok: 50,
    rating: 4.2,
  },
  {
    id: 4,
    nama_produk: "Sepatu Lari Speed",
    kategori: "Olahraga",
    harga: 850000,
    stok: 15,
    rating: 4.6,
  },
  {
    id: 5,
    nama_produk: "Tas Ransel Kanvas",
    kategori: "Aksesoris",
    harga: 350000,
    stok: 30,
    rating: 4.4,
  },
  {
    id: 6,
    nama_produk: "Smartwatch Z2",
    kategori: "Elektronik",
    harga: 1500000,
    stok: 40,
    rating: 4.3,
  },
  {
    id: 7,
    nama_produk: "Celana Chino Khaki",
    kategori: "Pakaian",
    harga: 300000,
    stok: 22,
    rating: 4.1,
  },
  {
    id: 8,
    nama_produk: "Botol Minum 1L",
    kategori: "Peralatan Rumah",
    harga: 75000,
    stok: 100,
    rating: 4.7,
  },
  {
    id: 9,
    nama_produk: "Headphone Wireless",
    kategori: "Elektronik",
    harga: 1200000,
    stok: 18,
    rating: 4.9,
  },
  {
    id: 10,
    nama_produk: "Jaket Bomber Black",
    kategori: "Pakaian",
    harga: 450000,
    stok: 12,
    rating: 4.5,
  },
  {
    id: 11,
    nama_produk: "Mouse Gaming RGB",
    kategori: "Elektronik",
    harga: 350000,
    stok: 60,
    rating: 4.6,
  },
  {
    id: 12,
    nama_produk: "Keyboard Mekanik",
    kategori: "Elektronik",
    harga: 750000,
    stok: 25,
    rating: 4.7,
  },
  {
    id: 13,
    nama_produk: "Monitor 24 Inch",
    kategori: "Elektronik",
    harga: 2100000,
    stok: 8,
    rating: 4.4,
  },
  {
    id: 14,
    nama_produk: "Kaos Polos Putih",
    kategori: "Pakaian",
    harga: 80000,
    stok: 200,
    rating: 4.2,
  },
  {
    id: 15,
    nama_produk: "Blender Juicer",
    kategori: "Peralatan Rumah",
    harga: 600000,
    stok: 15,
    rating: 4.3,
  },
  {
    id: 16,
    nama_produk: "Lampu Meja LED",
    kategori: "Peralatan Rumah",
    harga: 150000,
    stok: 45,
    rating: 4.5,
  },
  {
    id: 17,
    nama_produk: "Speaker Bluetooth",
    kategori: "Elektronik",
    harga: 550000,
    stok: 35,
    rating: 4.6,
  },
  {
    id: 18,
    nama_produk: "Rak Buku Minimalis",
    kategori: "Furnitur",
    harga: 1200000,
    stok: 5,
    rating: 4.8,
  },
  {
    id: 19,
    nama_produk: "Meja Kerja Kayu",
    kategori: "Furnitur",
    harga: 1800000,
    stok: 7,
    rating: 4.7,
  },
  {
    id: 20,
    nama_produk: "Kursi Gaming",
    kategori: "Furnitur",
    harga: 2500000,
    stok: 10,
    rating: 4.9,
  },
  {
    id: 21,
    nama_produk: "Kamera Mirrorless",
    kategori: "Elektronik",
    harga: 8500000,
    stok: 4,
    rating: 4.8,
  },
  {
    id: 22,
    nama_produk: "Lensa Prime 50mm",
    kategori: "Elektronik",
    harga: 3200000,
    stok: 6,
    rating: 4.7,
  },
  {
    id: 23,
    nama_produk: "Tripod Kamera",
    kategori: "Aksesoris",
    harga: 450000,
    stok: 20,
    rating: 4.5,
  },
  {
    id: 24,
    nama_produk: "Powerbank 20000mAh",
    kategori: "Elektronik",
    harga: 400000,
    stok: 80,
    rating: 4.6,
  },
  {
    id: 25,
    nama_produk: "Kabel Data Type-C",
    kategori: "Aksesoris",
    harga: 50000,
    stok: 300,
    rating: 4.8,
  },
  {
    id: 26,
    nama_produk: "Charger Mobil Fast",
    kategori: "Aksesoris",
    harga: 120000,
    stok: 50,
    rating: 4.4,
  },
  {
    id: 27,
    nama_produk: "SSD NVMe 500GB",
    kategori: "Elektronik",
    harga: 950000,
    stok: 40,
    rating: 4.9,
  },
  {
    id: 28,
    nama_produk: "RAM DDR4 16GB",
    kategori: "Elektronik",
    harga: 1100000,
    stok: 30,
    rating: 4.8,
  },
  {
    id: 29,
    nama_produk: "Harddisk Eksternal 1TB",
    kategori: "Elektronik",
    harga: 800000,
    stok: 25,
    rating: 4.6,
  },
  {
    id: 30,
    nama_produk: "Router Wi-Fi 6",
    kategori: "Elektronik",
    harga: 1300000,
    stok: 15,
    rating: 4.7,
  },
  {
    id: 31,
    nama_produk: "Rice Cooker Digital",
    kategori: "Peralatan Rumah",
    harga: 750000,
    stok: 18,
    rating: 4.5,
  },
  {
    id: 32,
    nama_produk: "Microwave Mini",
    kategori: "Peralatan Rumah",
    harga: 1400000,
    stok: 9,
    rating: 4.6,
  },
  {
    id: 33,
    nama_produk: "Vacuum Cleaner",
    kategori: "Peralatan Rumah",
    harga: 2200000,
    stok: 12,
    rating: 4.7,
  },
  {
    id: 34,
    nama_produk: "Air Purifier",
    kategori: "Peralatan Rumah",
    harga: 1850000,
    stok: 20,
    rating: 4.8,
  },
  {
    id: 35,
    nama_produk: "Setrika Uap",
    kategori: "Peralatan Rumah",
    harga: 450000,
    stok: 25,
    rating: 4.4,
  },
  {
    id: 36,
    nama_produk: "Handuk Mandi Tebal",
    kategori: "Peralatan Rumah",
    harga: 120000,
    stok: 60,
    rating: 4.6,
  },
  {
    id: 37,
    nama_produk: "Sprei Kasur King",
    kategori: "Peralatan Rumah",
    harga: 350000,
    stok: 15,
    rating: 4.5,
  },
  {
    id: 38,
    nama_produk: "Bantal Memory Foam",
    kategori: "Peralatan Rumah",
    harga: 280000,
    stok: 30,
    rating: 4.7,
  },
  {
    id: 39,
    nama_produk: "Gorden Jendela Grey",
    kategori: "Peralatan Rumah",
    harga: 200000,
    stok: 40,
    rating: 4.3,
  },
  {
    id: 40,
    nama_produk: "Karpet Ruang Tamu",
    kategori: "Furnitur",
    harga: 1100000,
    stok: 10,
    rating: 4.6,
  },
  {
    id: 41,
    nama_produk: "Topi Baseball Polos",
    kategori: "Aksesoris",
    harga: 75000,
    stok: 120,
    rating: 4.2,
  },
  {
    id: 42,
    nama_produk: "Kacamata Hitam UV",
    kategori: "Aksesoris",
    harga: 320000,
    stok: 45,
    rating: 4.5,
  },
  {
    id: 43,
    nama_produk: "Dompet Kulit Pria",
    kategori: "Aksesoris",
    harga: 250000,
    stok: 35,
    rating: 4.6,
  },
  {
    id: 44,
    nama_produk: "Ikat Pinggang Kulit",
    kategori: "Aksesoris",
    harga: 180000,
    stok: 50,
    rating: 4.4,
  },
  {
    id: 45,
    nama_produk: "Sarung Tangan Motor",
    kategori: "Aksesoris",
    harga: 135000,
    stok: 70,
    rating: 4.3,
  },
  {
    id: 46,
    nama_produk: "Jam Tangan Analog",
    kategori: "Aksesoris",
    harga: 950000,
    stok: 15,
    rating: 4.7,
  },
  {
    id: 47,
    nama_produk: "Kalung Perak 925",
    kategori: "Aksesoris",
    harga: 450000,
    stok: 20,
    rating: 4.5,
  },
  {
    id: 48,
    nama_produk: "Gelang Manik-manik",
    kategori: "Aksesoris",
    harga: 45000,
    stok: 150,
    rating: 4.1,
  },
  {
    id: 49,
    nama_produk: "Anting Hoop Gold",
    kategori: "Aksesoris",
    harga: 600000,
    stok: 10,
    rating: 4.6,
  },
  {
    id: 50,
    nama_produk: "Cincin Berlian Sintetis",
    kategori: "Aksesoris",
    harga: 1500000,
    stok: 5,
    rating: 4.8,
  },
  {
    id: 51,
    nama_produk: "Jersey Bola Timnas",
    kategori: "Olahraga",
    harga: 450000,
    stok: 30,
    rating: 4.7,
  },
  {
    id: 52,
    nama_produk: "Raket Badminton Pro",
    kategori: "Olahraga",
    harga: 1200000,
    stok: 12,
    rating: 4.9,
  },
  {
    id: 53,
    nama_produk: "Bola Basket Rubber",
    kategori: "Olahraga",
    harga: 250000,
    stok: 20,
    rating: 4.4,
  },
  {
    id: 54,
    nama_produk: "Matras Yoga TPE",
    kategori: "Olahraga",
    harga: 320000,
    stok: 40,
    rating: 4.6,
  },
  {
    id: 55,
    nama_produk: "Dumbbell 5kg (Sepasang)",
    kategori: "Olahraga",
    harga: 350000,
    stok: 15,
    rating: 4.5,
  },
  {
    id: 56,
    nama_produk: "Treadmill Elektrik",
    kategori: "Olahraga",
    harga: 6500000,
    stok: 3,
    rating: 4.8,
  },
  {
    id: 57,
    nama_produk: "Sepeda Gunung MTB",
    kategori: "Olahraga",
    harga: 4200000,
    stok: 5,
    rating: 4.7,
  },
  {
    id: 58,
    nama_produk: "Helm Sepeda Aman",
    kategori: "Olahraga",
    harga: 550000,
    stok: 25,
    rating: 4.6,
  },
  {
    id: 59,
    nama_produk: "Kacamata Renang Anti-Fog",
    kategori: "Olahraga",
    harga: 180000,
    stok: 50,
    rating: 4.4,
  },
  {
    id: 60,
    nama_produk: "Tas Olahraga Gym Bag",
    kategori: "Olahraga",
    harga: 280000,
    stok: 35,
    rating: 4.3,
  },
  {
    id: 61,
    nama_produk: "Serum Wajah Vitamin C",
    kategori: "Kecantikan",
    harga: 150000,
    stok: 80,
    rating: 4.7,
  },
  {
    id: 62,
    nama_produk: "Moisturizer Gel",
    kategori: "Kecantikan",
    harga: 125000,
    stok: 65,
    rating: 4.6,
  },
  {
    id: 63,
    nama_produk: "Sunscreen SPF 50",
    kategori: "Kecantikan",
    harga: 95000,
    stok: 100,
    rating: 4.8,
  },
  {
    id: 64,
    nama_produk: "Face Wash Gentle",
    kategori: "Kecantikan",
    harga: 75000,
    stok: 120,
    rating: 4.5,
  },
  {
    id: 65,
    nama_produk: "Masker Wajah Clay",
    kategori: "Kecantikan",
    harga: 65000,
    stok: 90,
    rating: 4.4,
  },
  {
    id: 66,
    nama_produk: "Lipstik Matte Red",
    kategori: "Kecantikan",
    harga: 110000,
    stok: 55,
    rating: 4.7,
  },
  {
    id: 67,
    nama_produk: "Foundation Liquid",
    kategori: "Kecantikan",
    harga: 185000,
    stok: 40,
    rating: 4.5,
  },
  {
    id: 68,
    nama_produk: "Palette Eyeshadow",
    kategori: "Kecantikan",
    harga: 250000,
    stok: 25,
    rating: 4.6,
  },
  {
    id: 69,
    nama_produk: "Parfum Eau de Toilette",
    kategori: "Kecantikan",
    harga: 550000,
    stok: 30,
    rating: 4.9,
  },
  {
    id: 70,
    nama_produk: "Hair Tonic Herbal",
    kategori: "Kecantikan",
    harga: 135000,
    stok: 45,
    rating: 4.3,
  },
  {
    id: 71,
    nama_produk: "Buku Resep Masakan",
    kategori: "Buku",
    harga: 120000,
    stok: 30,
    rating: 4.5,
  },
  {
    id: 72,
    nama_produk: "Novel Fiksi Best Seller",
    kategori: "Buku",
    harga: 95000,
    stok: 50,
    rating: 4.8,
  },
  {
    id: 73,
    nama_produk: "Buku Belajar Python",
    kategori: "Buku",
    harga: 180000,
    stok: 20,
    rating: 4.9,
  },
  {
    id: 74,
    nama_produk: "Komik Seri Terbaru",
    kategori: "Buku",
    harga: 45000,
    stok: 100,
    rating: 4.7,
  },
  {
    id: 75,
    nama_produk: "Ensiklopedia Anak",
    kategori: "Buku",
    harga: 350000,
    stok: 15,
    rating: 4.6,
  },
  {
    id: 76,
    nama_produk: "Action Figure Anime",
    kategori: "Mainan",
    harga: 850000,
    stok: 10,
    rating: 4.9,
  },
  {
    id: 77,
    nama_produk: "Puzzle 1000 Pieces",
    kategori: "Mainan",
    harga: 250000,
    stok: 25,
    rating: 4.5,
  },
  {
    id: 78,
    nama_produk: "Mobil Remote Control",
    kategori: "Mainan",
    harga: 550000,
    stok: 12,
    rating: 4.4,
  },
  {
    id: 79,
    nama_produk: "Boneka Beruang Besar",
    kategori: "Mainan",
    harga: 300000,
    stok: 20,
    rating: 4.6,
  },
  {
    id: 80,
    nama_produk: "Board Game Strategi",
    kategori: "Mainan",
    harga: 450000,
    stok: 15,
    rating: 4.8,
  },
  {
    id: 81,
    nama_produk: "Susu Bubuk 1kg",
    kategori: "Makanan & Minuman",
    harga: 135000,
    stok: 60,
    rating: 4.7,
  },
  {
    id: 82,
    nama_produk: "Kopi Arabika 500g",
    kategori: "Makanan & Minuman",
    harga: 110000,
    stok: 40,
    rating: 4.9,
  },
  {
    id: 83,
    nama_produk: "Teh Hijau Celup",
    kategori: "Makanan & Minuman",
    harga: 35000,
    stok: 150,
    rating: 4.6,
  },
  {
    id: 84,
    nama_produk: "Minyak Goreng 2L",
    kategori: "Makanan & Minuman",
    harga: 40000,
    stok: 200,
    rating: 4.5,
  },
  {
    id: 85,
    nama_produk: "Beras Premium 5kg",
    kategori: "Makanan & Minuman",
    harga: 85000,
    stok: 100,
    rating: 4.8,
  },
  {
    id: 86,
    nama_produk: "Pasta Makaroni 500g",
    kategori: "Makanan & Minuman",
    harga: 25000,
    stok: 80,
    rating: 4.4,
  },
  {
    id: 87,
    nama_produk: "Saus Sambal Ekstra Pedas",
    kategori: "Makanan & Minuman",
    harga: 15000,
    stok: 120,
    rating: 4.3,
  },
  {
    id: 88,
    nama_produk: "Cokelat Batangan Dark",
    kategori: "Makanan & Minuman",
    harga: 45000,
    stok: 70,
    rating: 4.7,
  },
  {
    id: 89,
    nama_produk: "Biskuit Gandum",
    kategori: "Makanan & Minuman",
    harga: 22000,
    stok: 90,
    rating: 4.5,
  },
  {
    id: 90,
    nama_produk: "Madu Hutan Murni",
    kategori: "Makanan & Minuman",
    harga: 160000,
    stok: 30,
    rating: 4.9,
  },
  {
    id: 91,
    nama_produk: "Obeng Set Multi",
    kategori: "Alat Pertukangan",
    harga: 125000,
    stok: 40,
    rating: 4.6,
  },
  {
    id: 92,
    nama_produk: "Bor Listrik Cordless",
    kategori: "Alat Pertukangan",
    harga: 850000,
    stok: 10,
    rating: 4.7,
  },
  {
    id: 93,
    nama_produk: "Tang Kombinasi",
    kategori: "Alat Pertukangan",
    harga: 55000,
    stok: 60,
    rating: 4.4,
  },
  {
    id: 94,
    nama_produk: "Meteran Baja 5m",
    kategori: "Alat Pertukangan",
    harga: 35000,
    stok: 80,
    rating: 4.5,
  },
  {
    id: 95,
    nama_produk: "Kunci Inggris Besar",
    kategori: "Alat Pertukangan",
    harga: 95000,
    stok: 35,
    rating: 4.6,
  },
  {
    id: 96,
    nama_produk: "Pupuk Tanaman Hias",
    kategori: "Taman",
    harga: 45000,
    stok: 100,
    rating: 4.5,
  },
  {
    id: 97,
    nama_produk: "Gunting Rumput",
    kategori: "Taman",
    harga: 85000,
    stok: 25,
    rating: 4.3,
  },
  {
    id: 98,
    nama_produk: "Pot Bunga Keramik",
    kategori: "Taman",
    harga: 120000,
    stok: 15,
    rating: 4.6,
  },
  {
    id: 99,
    nama_produk: "Selang Air 10m",
    kategori: "Taman",
    harga: 150000,
    stok: 30,
    rating: 4.4,
  },
  {
    id: 100,
    nama_produk: "Benih Sayuran Paket",
    kategori: "Taman",
    harga: 25000,
    stok: 200,
    rating: 4.7,
  },
];
